image:
- Visual Studio 2017

version: 0.1.0.{build}

# Only clone the current branch and no history
clone_depth: 1

pull_requests:
  # Do not increment build number for pull requests
  do_not_increment_build_number: true

nuget:
  # Do not publish NuGet packages for pull requests
  disable_publish_on_pr: true

environment:
  # Set the DOTNET_SKIP_FIRST_TIME_EXPERIENCE environment variable to stop wasting time caching packages
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending usage data to Microsoft
  DOTNET_CLI_TELEMETRY_OPTOUT: true

skip_commits:
  files:
    - readme.markdown

init:
  - git config --global core.autocrlf false

configuration:
  - Release

build_script:
  - dotnet restore ./src/PerformanceCounters.sln
  - dotnet build ./src/PerformanceCounters.sln --configuration Release
  - dotnet pack ./src/PerformanceCounters/PerformanceCounters.csproj --configuration Release --no-restore --no-build -p:PackageVersion=%APPVEYOR_BUILD_VERSION%

deploy: off
  #provider: NuGet
  #api_key:
  #  secure: m49OJ7+Jdt9an3jPcTukHA==
  #skip_symbols: false
  #artifact: /.*\.nupkg/